{"name": "test_basic_02", "status": "broken", "statusDetails": {"message": "requests.exceptions.InvalidSchema: No connection adapters were found for '\"http://192.168.3.21:30236/auth/login/\"'", "trace": "self = <test_basic.TestBasic object at 0x110ef5048>, action = 'debug'\n\n    @allure.severity('blocker')\n    @allure.story('Basic')\n    def test_basic_02(self, action):\n        \"\"\"\n            用例描述：登陆状态下查看基础设置\n        \"\"\"\n        conf = Config()\n        data = Basic()\n        test = Assert.Assertions()\n>       request = Send_Request.Request(action)\n\nTestCase/test_basic.py:54: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nCommon/Send_Request.py:27: in __init__\n    self.get_session = self.session.get_session(env)\nCommon/Session.py:41: in get_session\n    response = session_debug.post(login_url, parm, headers=headers)\n/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py:555: in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py:508: in request\n    resp = self.send(prep, **send_kwargs)\n/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py:612: in send\n    adapter = self.get_adapter(url=request.url)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <requests.sessions.Session object at 0x110ef5c50>, url = '\"http://192.168.3.21:30236/auth/login/\"'\n\n    def get_adapter(self, url):\n        \"\"\"\n        Returns the appropriate connection adapter for the given URL.\n    \n        :rtype: requests.adapters.BaseAdapter\n        \"\"\"\n        for (prefix, adapter) in self.adapters.items():\n    \n            if url.lower().startswith(prefix):\n                return adapter\n    \n        # Nothing matches :-/\n>       raise InvalidSchema(\"No connection adapters were found for '%s'\" % url)\nE       requests.exceptions.InvalidSchema: No connection adapters were found for '\"http://192.168.3.21:30236/auth/login/\"'\n\n/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py:703: InvalidSchema"}, "description": "\n            用例描述：登陆状态下查看基础设置\n        ", "start": 1586834273007, "stop": 1586834273014, "uuid": "f54bfe62-b39a-476d-bc51-92541ee021e2", "historyId": "00cf352422e4e739b9079d72fc93ad96", "testCaseId": "1bc9621ed29be39d8aa389abbd6af750", "fullName": "TestCase.test_basic.TestBasic#test_basic_02", "labels": [{"name": "severity", "value": "blocker"}, {"name": "story", "value": "Basic"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_basic"}, {"name": "subSuite", "value": "TestBasic"}, {"name": "host", "value": "Lettos-iMac.local"}, {"name": "thread", "value": "45573-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_basic"}]}